# numpy tutorials

Numpy is the fundamental building block of many of the later developed python packages for data science and other scientific applciations. Numpy is primarily concerned with array operations and will come as a handy tool while manipulating many of the text arrays, strings and documents that we will be operating on. 

The advantage of using numpy over python tupples and lists is that numpy arrays occupy less RAM as compared to vanilla python lists/tupples. In addition to this, use of numpy operations is a great and faster replacement for python 'for' loops

Lets begin by importing the preinstalled numpy package and trying to create our first numpy array

In [1]:
import numpy as np
a=np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [2]:
a=np.arange(20).reshape(5,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


Let us now understand some of the attributes of the above numpy array

In [3]:
a.shape

(5, 4)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int32'

In [8]:
a.itemsize

4

In [6]:
a.size

20

In [7]:
type(a)

numpy.ndarray

There are several ways to create an array in numpy

In [8]:
a=np.array([1,2,3,4])
print(a.dtype.name)
b=np.array([1.1,2.3,4.5,6.8])
print(b.dtype.name)
c=np.array([(1,2,3,4),(1,2,4,6)])
print(c.dtype.name)
print(c.shape)

int32
float64
int32
(2, 4)


We will explore more ways of creating numpy arrays in our next notebook