### Intrisic NumPy array creation

In [2]:
import numpy as np

In [3]:
integers_array=np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
integers_second_array=np.arange(100,130)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [5]:
integers_third_array=np.arange(100,151,2)
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [6]:
first_floats_arr=np.linspace(10,20)
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [24]:
second_floats_arr=np.linspace(10,30,10)
print(second_floats_arr)


[10.         12.22222222 14.44444444 16.66666667 18.88888889 21.11111111
 23.33333333 25.55555556 27.77777778 30.        ]


In [20]:
np.arange(10,31,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [27]:
first_rand_arr=np.random.rand(10)
first_rand_arr

array([0.81358376, 0.41426019, 0.36491461, 0.34358864, 0.50104116,
       0.95616226, 0.30098989, 0.89731762, 0.5978374 , 0.38193962])

In [28]:
second_rand_arr=np.random.rand(4,4)
second_rand_arr

array([[0.21043032, 0.66589998, 0.22115833, 0.9924869 ],
       [0.06398781, 0.1254229 , 0.76660309, 0.45868385],
       [0.96198417, 0.70890624, 0.82262629, 0.64616658],
       [0.94545316, 0.90787879, 0.41170501, 0.11014996]])

In [30]:
third_rand_arr=np.random.randint(0,100,size=(5,4))
third_rand_arr

array([[11, 59, 92, 53],
       [61, 50, 54, 86],
       [45, 13, 45, 19],
       [ 1, 35, 55, 80],
       [67, 80, 49, 14]])